---
title: "Untitled"
output: html_document
date: "2023-07-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| **Week** | **Readings Due by Class Time**                                                                                                                                        | **Data Used**         |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1        | Substantive reading:                                                                                                                                                  | starwars              |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 2        | Substantive reading:                                                                                                                                                  | usafacts.org          |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
|          |                                                                                                                                                                       |                       |
|          | -   4.1 and 4.2: \<<https://bookdown.or> g/rdpeng/RProgDA/basic-pl otting-with-ggplot2.html\>                                                                         |                       |
|          |                                                                                                                                                                       |                       |
|          | -   \<<https://r4ds.had>. co.nz/data-visualisation. html#data-visualisation\>                                                                                         |                       |
|          |                                                                                                                                                                       |                       |
|          | -   \<h [ttps://rc2e.com/graphics](ttps://rc2e.com/graphics)                                                                                                          |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| : 3      | Substantive reading: xx                                                                                                                                               | crowdtangle           |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
|          |                                                                                                                                                                       |                       |
|          | -   \<<https://www.guru99.com> /r-dplyr-tutorial.html#2\> (join with dplyr)                                                                                           |                       |
|          |                                                                                                                                                                       |                       |
|          | -   \<https ://bookdown.org/rwnahhas/ IntroToR/merge-join.html\>                                                                                                      |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 4        | Substantive reading:                                                                                                                                                  |                       |
|          |                                                                                                                                                                       |                       |
|          | -   Data Feminism Chapter 6?                                                                                                                                          |                       |
|          |                                                                                                                                                                       |                       |
|          | -   Social Media Research: A Guide to Ethics (Dr. Townsend, Univ. of Aberdeen) (\<h [ttps://www.gla.ac.uk/medi](ttps://www.gla.ac.uk/medi) a/Media_487729_smxx.pdf\>) |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
|          |                                                                                                                                                                       |                       |
|          | -   Rosenberg et al. (ETRD)                                                                                                                                           |                       |
|          |                                                                                                                                                                       |                       |
|          | -   It would be good to have a discussion about the ever-changing API access (e.g., Twitter changed their API access)                                                 |                       |
|          |                                                                                                                                                                       |                       |
|          | -   [https:/ocean.sagepub. com/blog/collecting-socia l-media-data-for-research](https://ocean.sagepub.c%20om/blog/collecting-social%20-media-data-for-research)       |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 5        | Substantive reading: xx                                                                                                                                               | Wikipedia             |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
|          |                                                                                                                                                                       |                       |
|          | -   \<https: //towardsdatascience.com/ scraping-data-from-wikipe dia-tables-3efa04c6b53f\>                                                                            |                       |
|          |                                                                                                                                                                       |                       |
|          | -    \<<https://www.r-bloggers>. com/2021/07/politely-scra ping-wikipedia-tables-2/\>                                                                                 |                       |
|          |                                                                                                                                                                       |                       |
|          | -   \<<https://dcl-wrangle> .stanford.edu/rvest.html\>                                                                                                                |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 6        | Substantive reading: xx                                                                                                                                               | Own or other provided |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
|          |                                                                                                                                                                       |                       |
|          | -   R4DS:[https://r4ds .hadley.nz/data-transform .html](https://r4ds.hadle%20y.nz/data-transform.html)                                                                |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 7        | Substantive reading: xx                                                                                                                                               | Own or other provided |
|          |                                                                                                                                                                       |                       |
|          | Technical reading:                                                                                                                                                    |                       |
|          |                                                                                                                                                                       |                       |
|          | -   R4DS:[https://r4ds .hadley.nz/data-transform .html](https://r4ds.hadle%20y.nz/data-transform.html)                                                                |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 8        | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 9        | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 0      | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 1      | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 2      | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 3      | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 4      | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 5      | Week 16 Reading and Discussing                                                                                                                                        |                       |
|          |                                                                                                                                                                       |                       |
|          | Substantive reading: xx                                                                                                                                               |                       |
|          |                                                                                                                                                                       |                       |
|          | Technical reading: xx                                                                                                                                                 |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| 1 6      | \-                                                                                                                                                                    |                       |
+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
