---
title: "STEM 580: An Introduction to Data Science Methods in Education - Syllabus"
output:
  pdf_document: default
  html_document: default
date: "Last updated: 2023-07-08"
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Key Information

### **Meeting Time and Place**

Mondays, 12:00 - 2:30 pm (online and synchronous; see schedule below for
specific class dates)

### Credit Hours

3

### Faculty Contact Information

*Dr. Isabella Velasquez*

*Dr. Maryrose Weatherton*

### Course Links

Zoom: [MR to setup, add link]

Slack: [thoughts -- don't want to overwhelm students, but think it's a
good idea]

GitHub: <https://github.com/utkeds/f23-founds-eds-1>

Canvas: <https://utk.instructure.com/courses/184613>

### Course Description

Intended to support graduate-level students to be able to apply data
science methods to topics of teaching, learning, and educational
systems. Introduces students to the data science software and
programming language R. Course activities focusing on preparing, using,
and visualizing complex data sources for analysis using the tidyverse
suite of R packages. Data ethics are foregrounded. Includes an
introduction to text analysis/Natural Language Processing. No
pre-requisites or programming experience is required.

A key element of this class is that students will have the opportunity
to bring their own data from their research projects for use in this
class. In this way, they will have immediate application for the
concepts learned in the course. If no data is immediately available from
the student's research, students can use one of hundreds of freely
available datasets to complete coursework or students can use datasets
provided to them.

In all, this course will provide scaffolding to help students become
proficient in a few sophisticated data science techniques, and it will
give students sufficient foundational knowledge to pick up new data
science skills on their own after the course is through. This course
will serve as a foundation for later data science in education,
including the second foundations class, data visualization, and machine
learning and the capstone course.

### Learning Objectives

The objectives for the proposed course are for students to be able to:

-   Install, set up, and use R and RStudio

-   Use reproducible workflows (so that analyses can easily be modified
    and then carried out again by the analyst or others) with R Markdown

-   Develop foundational skills - focused around the tidyverse R
    packages - to prepare and explore data sources for analysis

-   Understand how issues of equity, privacy, and ethics are central to
    data science in education

-   Develop a personal learning and development plan related to data
    science in education

-   Begin a portfolio of work from this class that you can add to later

-   Pursue an independent project to work toward a relevant professional
    goal

## Format and Learning Environment

This class will be taught in a fully-online format. We will use Zoom for
synchronous (or at-the-same-time) class. We will also use a number of
tools for asynchronous communication, including a) Slack, b) GitHub, and
c) features of the Canvas course learning management system.

## Communication

You will generally receive a response to messages within 24 hours during
the work week (Monday - Friday). We ask for you to please try to respond
within 24 hours during the work week, too. You can contact us via email
(above) or Slack (preferred).

## How to Be Successful in This Course

Don't hesitate to ask questions! Learning to do data science is
challenging for everyone, and reaching out for support and assistance is
imperative. My late assignment policy is that as long as you submit the
assignment before we grade it, you will receive full credit. However, we
may grade assignments very soon after they are due. For assignments
received after the due date, 5% from the grade you otherwise would earn
will be subtracted from your final grade for each day late.

## Required Equipment

You will need a computer (Mac, Windows, or Linux are fine!) on which you
can install applications, but you do not need a computer with any
particular specifications (speed, storage, etc.) beyond what you use for
other courses: whatever you have will work for this course.

## Grading Scale

| LETTER GRADE | PERCENTAGE   |
|--------------|--------------|
| A            | 93.01-100    |
| A-           | 90.01-93     |
| B+           | 87.01-90     |
| B            | 83.01-87     |
| B-           | 80.01-83     |
| C+           | 77.01-80     |
| C            | 73.01-77     |
| C-           | 70.01-73     |
| D            | 60.01-70     |
| F            | 60 and below |

## Course Grade

+------------------+----------------+-------------------------+
| ASSIGNMENT       | PERCENT OF     | POINTS                  |
|                  | GRADE          |                         |
+==================+================+=========================+
| Readings         | 12.5%          | 10 / week for 15 weeks  |
|                  |                | = 150 points            |
|                  |                |                         |
|                  |                | \*no reading in Week 16 |
+------------------+----------------+-------------------------+
| Weekly           | 32.5%          | 30 / week for 13 weeks  |
| Assignments      |                | = 390 points            |
|                  |                |                         |
|                  |                | \*no assignment Weeks   |
|                  |                | 1, 9, and 16            |
+------------------+----------------+-------------------------+
| Professional     | 5%             | 60                      |
| Development Plan |                |                         |
+------------------+----------------+-------------------------+
| Mini Project     | 12.5%          | 150                     |
+------------------+----------------+-------------------------+
| Data Ethics      | 12.5%          | 150                     |
| Statement        |                |                         |
+------------------+----------------+-------------------------+
| Final Project    | 25%            | 300                     |
+------------------+----------------+-------------------------+
| Total:           | 100%           | 1,200                   |
+------------------+----------------+-------------------------+

## Learning Activities

-   **Participation: weekly classes.** Each class will have a consistent
    structure.

    -   *Complete reading, discussion, and any assignment(s)* before
        class

    -   *Answer the eliciting question* in groups at the beginning of
        each class and discuss as a class (30 minutes)

    -   Listen, answer questions, and code-along with the *introducing
        new ideas* portion of class (30 minutes)

    -   *Code-along* using built-in data to get a feel for the code you
        will be using (30 minutes)

    -   Time to *start on the assignment for the next week with a
        peer/peers* (30 minutes)

    -   Ask any questions or have independent work time (30 minutes)

-   **In-class programming.** At the core of this class is programming
    in R. We will develop R programming skills for data wrangling,
    exploration, and visualization together by doing various in-class
    programming activities. We will complete these activities as a whole
    class, in small groups, or in pairs. Semi-structured activities will
    give us a chance to discuss, better understand, and practice our
    programming skills.

-   **Weekly assignments**: Weekly tasks that involve combining reading
    about relevant theory and prior research, working through
    fundamentals in a guided practice model. These will be submitted as
    R documents, HTML files, or images. 

-   **Mini project:** This independent project will involve the
    application of theory and programming to create various
    visualizations from an already-existing data set. Your work will be
    shared with other students and the instructor to provide you with
    opportunities to provide and receive constructive critique (and to
    revise your work, as is the case with all visualizations!).

-   **Data ethics statement:** You will explore visualizations created
    by others for #tidytuesday and apply newly learned skills together
    with the theory and programming learned in class to a provided data
    set to create various visualizations from a provided data set. Your
    work will be shared with other students and the instructor to
    provide you with opportunities to provide and receive constructive
    critique and revise your work.

-   **Professional development plan:** Develop a plan for your continued
    professional data science learning.

-   **Final project:** You will complete a final project that involves
    developing visualizations for your own data or a data set of your
    choice. The goal of this project is to create a publication-ready
    visualization that demonstrates what you have learned throughout the
    course.

## Generative Artificial Intelligence

Open AI's GPT-4 and other generative artificial intelligence tools like
it (e.g., Google's Bard) can be immensely helpful when it comes to
programming in R and other languages. We encourage their use, but ask
that you add a note to anything you submit in which you have used a
generative artificial intelligence tool about how you have used it to
provide context to us and to help us to learn how these tools are
useful.

## Timeline

+-------------+-------------+-------------+------------------+
| -           | **Date**    | **Focal     | **Assignments    |
|  \*Semester |             | Question    | Due Before the   |
|     W       |             | and Topic** | Next Class**     |
|     eek\*\* |             |             |                  |
+-------------+-------------+-------------+------------------+
| 1           | N/A         | What's R?   | Primers          |
|             |             | Getting     |                  |
|             |             | Setup       | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 2           | August 28   | What's this | Week 2           |
|             |             | course      | Assignment:      |
|             |             | about?      | Install R and R  |
|             |             | Introducing | Studio, Simple   |
|             |             | the course  | code             |
|             |             | and         | walkthrough; use |
|             |             | ourselves   | janitor, "skim"  |
|             |             |             | a data set to    |
|             |             |             | get a feel for   |
|             |             |             | the data, **and  |
|             |             |             | answer some      |
|             |             |             | questions**      |
|             |             |             | (what's the      |
|             |             |             | average? what's  |
|             |             |             | your state?      |
|             |             |             | what's the max?  |
|             |             |             | min?) with NAEP  |
|             |             |             | state-level data |
|             |             |             |                  |
|             |             |             | Slides: which    |
|             |             |             | state performs   |
|             |             |             | best? why? what  |
|             |             |             | does best mean?  |
|             |             |             | introduce        |
|             |             |             | janitor, skim,   |
|             |             |             | reading in a     |
|             |             |             | data set; code,  |
|             |             |             | code chunks, the |
|             |             |             | coding process;  |
|             |             |             | create an R      |
|             |             |             | Markdown file    |
|             |             |             |                  |
|             |             |             | In-class         |
|             |             |             | code-along: read |
|             |             |             | data, use        |
|             |             |             | janitor, use     |
|             |             |             | skimr            |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 3           | September 4 | What's all  | Week 3           |
|             |             | the fuss    | Assignment:      |
|             |             | about data  | Creating faceted |
|             |             | science?    | plots with       |
|             |             | Doing       | ggplot2 - drill  |
|             |             | things we   | down into        |
|             |             | could not   | group-specific   |
|             |             | easily do   | *patterns*       |
|             |             | without     | within federal   |
|             |             | advanced    | school data      |
|             |             | *graphics*  |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 4           | September   | What's all  | Week 4           |
|             | 11          | the fuss    | Assignment:      |
|             |             | about data  | Joining multiple |
|             |             | science?    | frames -- join   |
|             |             | Doing       | two unrelated    |
|             |             | things we   | data sets        |
|             |             | could not   | together and     |
|             |             | easily do   | examine the      |
|             |             | without     | correlation -    |
|             |             | *coding*    | tidykids         |
|             |             |             | spending - pk12  |
|             |             |             | spending relates |
|             |             |             | to NAEP          |
|             |             |             | performance?     |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 5           | September   | How do I    | Week 5           |
|             | 18          | access and  | Assignment:      |
|             |             | describe    | Accessing and    |
|             |             | data? Using | describing       |
|             |             | an R        | data - using the |
|             |             | package and | educationdata    |
|             |             | an API      | package to query |
|             |             |             | an API           |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 6           | September   | How do I    | Week 6           |
|             | 25          | preparing   | Assignment:      |
|             |             | data for    | Foundational     |
|             |             | analysis ?F | data wrangling,  |
|             |             | oundational | part 1 - Making  |
|             |             | skills,     | a better college |
|             |             | Part 1a     | rating using     |
|             |             |             | college data -   |
|             |             |             | using            |
|             |             |             | educationdata    |
|             |             |             | co               |
|             |             |             | llege-university |
|             |             |             | end points       |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 7           | October 2   | How do I    | Week 7           |
|             |             | group and   | Assignment:      |
|             |             | summarize   | Foundational     |
|             |             | data? F     | data wrangling,  |
|             |             | oundational | part 2, Making a |
|             |             | skills,     | better college   |
|             |             | Part 1b     | rating using     |
|             |             |             | college data -   |
|             |             |             | using            |
|             |             |             | educationdata    |
|             |             |             | co               |
|             |             |             | llege-university |
|             |             |             | end points       |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 8           | October 9   | N/A         | Weekly reading   |
|             | (Fall       |             | and discussion   |
|             | Break)      |             |                  |
+-------------+-------------+-------------+------------------+
| 9           | October 16  | How do I    | Week 9           |
|             |             | access      | Assignment,      |
|             |             | public      | Scraping         |
|             |             | Internet    | Wikipedia        |
|             |             | data? Web   |                  |
|             |             | scraping    | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 10          | October 23  | What have I | Mini Project --  |
|             |             | done?!?     | \< \<https:      |
|             |             | Sharing     | //dat            |
|             |             | work        | a.utk.edu/\>\> - |
|             |             | (Quarto,    | Calculating      |
|             |             | Rmd and its | descriptive      |
|             |             | friends)    | stats from a     |
|             |             | and         | survey to share  |
|             |             | Presenting  | with instructors |
|             |             | Mini        | and              |
|             |             | Project     | administrators   |
|             |             |             | OR Making a      |
|             |             |             | better college   |
|             |             |             | rating using     |
|             |             |             | college data OR  |
|             |             |             | Use student      |
|             |             |             | performance data |
|             |             |             | over several     |
|             |             |             | years to         |
|             |             |             | identify trends, |
|             |             |             | make             |
|             |             |             | predictions, and |
|             |             |             | recommend        |
|             |             |             | interventions    |
|             |             |             | for at-risk      |
|             |             |             | students         |
|             |             |             |                  |
|             |             |             | Week 10          |
|             |             |             | Assignment,      |
|             |             |             | Create a report  |
|             |             |             | based on your    |
|             |             |             | mini project     |
|             |             |             | analysis         |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 11          | October 30  | What are    | Week 11          |
|             |             | the more    | Assignment,      |
|             |             | complex     | Advanced data    |
|             |             | skills I    | wrangling and    |
|             |             | need to     | visualization,   |
|             |             | work with   | part 1 -         |
|             |             | data? F     | **Building a     |
|             |             | oundational | dashboard using  |
|             |             | skills,     | learning         |
|             |             | Part 2a     | analytics data - |
|             |             |             | candidate -**    |
|             |             |             | prep for the     |
|             |             |             | dashboard;       |
|             |             |             | getting teh data |
|             |             |             | ready            |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 12          | November 6  | What are    | Week 12          |
|             |             | the core    | Assignment,      |
|             |             | skills I    | Advanced data    |
|             |             | need to     | wrangling and    |
|             |             | work with   | visualization,   |
|             |             | data? F     | part 2 -         |
|             |             | oundational | building a beta  |
|             |             | skills,     | version of       |
|             |             | Part 2b     | dashboard with a |
|             |             |             | single plot      |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 13          | November 13 | How can I   | Week 13          |
|             |             | prepare for | Assignment,      |
|             |             | the final   | Mapping          |
|             |             | project?    | Achievement      |
|             |             | Learning    | Gaps: Use school |
|             |             | more and    | performance data |
|             |             | creating    | and district     |
|             |             | data        | shape files to   |
|             |             | products    | create a map to  |
|             |             |             | understand       |
|             |             |             | achievement      |
|             |             |             | gaps. - Creating |
|             |             |             | an interactive   |
|             |             |             | map -            |
|             |             |             | \<<https://gi>   |
|             |             |             | thub.            |
|             |             |             | com/             |
|             |             |             | ivelasq/leaidr\> |
|             |             |             | and\             |
|             |             |             | \<<ht            |
|             |             |             | tps://www.tn.go> |
|             |             |             | v/education/dis  |
|             |             |             | tric             |
|             |             |             | ts/f             |
|             |             |             | ederal-programs- |
|             |             |             | and-oversight/da |
|             |             |             | ta/d             |
|             |             |             | ata-             |
|             |             |             | downloads.html\> |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 14          | November 20 | How can I   | Week 14          |
|             |             | use text as | Assignment, Text |
|             |             | data?       | analysis, part   |
|             |             | Tokens and  | 1 - social media |
|             |             | frequencies | data...          |
|             |             |             | CrowdTangle data |
|             |             |             | on climate       |
|             |             |             | change (you can  |
|             |             |             | parse for        |
|             |             |             | educational      |
|             |             |             | implications or  |
|             |             |             | broader/other    |
|             |             |             | implications)    |
|             |             |             |                  |
|             |             |             | Accessing and    |
|             |             |             | describing       |
|             |             |             | social media and |
|             |             |             | public internet  |
|             |             |             | data             |
|             |             |             |                  |
|             |             |             | Data Ethics      |
|             |             |             | Statement        |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 15          | November 27 | How can I   | Week 15          |
|             |             | use text as | Assignment, Text |
|             |             | data?       | analysis, part   |
|             |             | Sentiment   | 2 - student      |
|             |             | and term c  | comments (Ryan   |
|             |             | ooccurences | and/or Rita and  |
|             |             |             | Josh)            |
|             |             |             |                  |
|             |             |             | Accessing and    |
|             |             |             | describing       |
|             |             |             | social media and |
|             |             |             | public internet  |
|             |             |             | data             |
|             |             |             |                  |
|             |             |             | Weekly reading   |
|             |             |             | and discussion   |
+-------------+-------------+-------------+------------------+
| 16          | December 4  | Final       | Weekly reading   |
|             |             | Projects    | and discussion   |
+-------------+-------------+-------------+------------------+

## Readings

+-------------+-------------+-------------+--------------------+
| *           | -           |             | **Tutorial         |
| *DaSemester |  \*Date\*\* | **          | Reading(s)**       |
| Week**      |             | Substantive |                    |
|             |             | R           |                    |
|             |             | eading(s)** |                    |
+-------------+-------------+-------------+--------------------+
| 1           | N/A         | Estrellado, | R Primers:         |
|             |             | R. A.,      |                    |
|             |             | Freer, E.   | <                  |
|             |             | A.,         | https://posit.clou |
|             |             | Mostipak,   | d/learn/primers/1> |
|             |             | J.,         |                    |
|             |             | Rosenberg,  | <                  |
|             |             | J. M., &    | https://posit.clou |
|             |             | Velásquez,  | d/learn/primers/2> |
|             |             | I. C.       |                    |
|             |             | (2020).     |                    |
|             |             | Data        |                    |
|             |             | science in  |                    |
|             |             | education   |                    |
|             |             | using R.    |                    |
|             |             | Routledge.  |                    |
|             |             | Chapter 3,  |                    |
|             |             | What does   |                    |
|             |             | data        |                    |
|             |             | science in  |                    |
|             |             | education   |                    |
|             |             | look like?  |                    |
|             |             | \<<http     |                    |
|             |             | s://datasc> |                    |
|             |             | ienc        |                    |
|             |             | eineducatio |                    |
|             |             | n.com       |                    |
|             |             | /c03.html\> |                    |
|             |             |             |                    |
|             |             | McFarland,  |                    |
|             |             | D. A.,      |                    |
|             |             | Khanna, S., |                    |
|             |             | Domingue,   |                    |
|             |             | B. W., &    |                    |
|             |             | Pardos, Z.  |                    |
|             |             | A. (2021).  |                    |
|             |             | Education   |                    |
|             |             | data        |                    |
|             |             | science:    |                    |
|             |             | Past,       |                    |
|             |             | present,    |                    |
|             |             | future.     |                    |
|             |             | AERA Open,  |                    |
|             |             | 7, 233 2858 |                    |
|             |             | 4211052055. |                    |
+-------------+-------------+-------------+--------------------+
| 2           | August 28   | Salganik,   | Creating and using |
|             |             | M. J.       | a .Rmd file        |
|             |             | (2019). Bit |                    |
|             |             | by bit:     | R for Data         |
|             |             | Social      | Science, Chapter   |
|             |             | research in | 2:                 |
|             |             | the digital | <https:/           |
|             |             | age.        | /r4ds.hadley.nz/da |
|             |             | Princeton   | ta-visualize.html> |
|             |             | University  |                    |
|             |             | Press.      | Cleaning names     |
|             |             | Chapters 2  | with Janitor:      |
|             |             | (Observing  | <htt               |
|             |             | Behavior)   | ps://bookdown.org/ |
|             |             | and 3       | aschmi11/RESMHandb |
|             |             | (Asking     | ook/data-preparati |
|             |             | Questions). | on-and-cleaning-in |
|             |             |             | -r.html#cleaning-n |
|             |             |             | ames-with-janitor> |
+-------------+-------------+-------------+--------------------+
| 3           | Se ptember  | Lang, C.,   | R 4 Data Science,  |
|             | 4           | Wise, A.    | Chapter 2 ggplot2  |
|             |             | F.,         | tutorial:          |
|             |             | Merceron,   | <ht                |
|             |             | A.,         | tps://r4ds.hadley. |
|             |             | Gasevic,    | nz/data-visualize. |
|             |             | D., &       | html#introduction> |
|             |             | Siemens, G. |                    |
|             |             | (2022).     | Data Visualization |
|             |             | What is     | introduction from  |
|             |             | learning    | Modern Dive:       |
|             |             | analytics.  | <ht                |
|             |             | The         | tps://moderndive.c |
|             |             | handbook of | om/2-viz.html#viz> |
|             |             | learning    |                    |
|             |             | analytics,  |                    |
|             |             | 8-18.       |                    |
|             |             |             |                    |
|             |             | Rutherford, |                    |
|             |             | T., Duck,   |                    |
|             |             | K.,         |                    |
|             |             | Rosenberg,  |                    |
|             |             | J. M., &    |                    |
|             |             | Patt, R.    |                    |
|             |             | (2022).     |                    |
|             |             | Leveraging  |                    |
|             |             | mathematics |                    |
|             |             | software    |                    |
|             |             | data to     |                    |
|             |             | understand  |                    |
|             |             | student     |                    |
|             |             | learning    |                    |
|             |             | and         |                    |
|             |             | motivation  |                    |
|             |             | during the  |                    |
|             |             | COVID-19    |                    |
|             |             | pandemic.   |                    |
|             |             | Journal of  |                    |
|             |             | Research on |                    |
|             |             | Technology  |                    |
|             |             | in          |                    |
|             |             | Education,  |                    |
|             |             | 54(sup1),   |                    |
|             |             | S94-S131.   |                    |
+-------------+-------------+-------------+--------------------+
| 4           | Se ptember  | Worsley,    | R 4 Data Science,  |
|             | 11          | M., Mart    | Chapter 20 joining |
|             |             | inez        | tables:            |
|             |             | -Maldonado, | <https://r4ds.had  |
|             |             | R., &       | ley.nz/joins.html> |
|             |             | D'Angelo,   |                    |
|             |             | C. (2021).  | Joining tables     |
|             |             | A New Era   | tutorial:          |
|             |             | in          | <h                 |
|             |             | Multimodal  | ttps://hollyemblem |
|             |             | Learning    | .medium.com/joinin |
|             |             | Analytics:  | g-data-with-dplyr- |
|             |             | Twelve Core | in-r-874698eb8898> |
|             |             | Commitments |                    |
|             |             | to Ground   |                    |
|             |             | and Grow    |                    |
|             |             | MMLA.       |                    |
|             |             | Journal of  |                    |
|             |             | Learning    |                    |
|             |             | Analytics,  |                    |
|             |             | 8(3),       |                    |
|             |             | 10-27.      |                    |
+-------------+-------------+-------------+--------------------+
| 5           | Se ptember  | Reich, J.   | Query an API using |
|             | 18          | (2022).     | R:                 |
|             |             | Learning    |                    |
|             |             | analytics   | [https://medi      |
|             |             | and         | um.com/\@traffordD |
|             |             | learning at | ataLab/querying-ap |
|             |             | scale.      | is-in-r-39029b73d5 |
|             |             | Lang, C.,   | f1](https://medium |
|             |             | Siemens, G. | .com/@traffordData |
|             |             | Wise, AF,   | Lab/querying-apis- |
|             |             | Gašević,    | in-r-39029b73d5f1) |
|             |             | D.,         |                    |
|             |             | Merceron,   | <http://lab.rady.u |
|             |             | A.,(eds.)   | csd.edu/sawtooth/b |
|             |             | Handbook of | usiness_analytics_ |
|             |             | Learning    | in_r/DataApi.html> |
|             |             | Analytics,  |                    |
|             |             | 2nd ed.     |                    |
|             |             | Vancouver,  |                    |
|             |             | Canada:     |                    |
|             |             | SOLAR.      |                    |
|             |             |             |                    |
|             |             | White, R.   |                    |
|             |             | S. (2023).  |                    |
|             |             | What's in a |                    |
|             |             | first       |                    |
|             |             | name?:      |                    |
|             |             | America's   |                    |
|             |             | K-12 public |                    |
|             |             | school      |                    |
|             |             | district    |                    |
|             |             | sup         |                    |
|             |             | erintendent |                    |
|             |             | gender gap. |                    |
|             |             | Leadership  |                    |
|             |             | and Policy  |                    |
|             |             | in Schools, |                    |
|             |             | 22(2),      |                    |
|             |             | 385-401.    |                    |
+-------------+-------------+-------------+--------------------+
| 6           | Se ptember  | Shelton, C. | Data Science in    |
|             | 25          | C.,         | Education, Chapter |
|             |             | Koehler, M. | 6:                 |
|             |             | J.,         | <htt               |
|             |             | Greenhalgh, | ps://datasciencein |
|             |             | S. P., &    | education.com/c06> |
|             |             | Carpenter,  |                    |
|             |             | J. P.       | R 4 Data Science,  |
|             |             | (2022).     | Chapter 4:         |
|             |             | Lifting the |                    |
|             |             | veil on     | <ht                |
|             |             | Teach ersP  | tps://r4ds.hadley. |
|             |             | ayTeachers. | nz/data-transform> |
|             |             | com: An in  |                    |
|             |             | vestigation |                    |
|             |             | of          |                    |
|             |             | educational |                    |
|             |             | marketplace |                    |
|             |             | offerings   |                    |
|             |             | and         |                    |
|             |             | downloads.  |                    |
|             |             | Learning,   |                    |
|             |             | Media and   |                    |
|             |             | Technology, |                    |
|             |             | 47(2),      |                    |
|             |             | 268-287.    |                    |
|             |             |             |                    |
|             |             | Rosenberg,  |                    |
|             |             | J. M.,      |                    |
|             |             | Borchers,   |                    |
|             |             | C.,         |                    |
|             |             | Burchfield, |                    |
|             |             | M. A.,      |                    |
|             |             | Anderson,   |                    |
|             |             | D.,         |                    |
|             |             | Stegenga,   |                    |
|             |             | S. M., &    |                    |
|             |             | Fischer, C. |                    |
|             |             | (2022).     |                    |
|             |             | Posts about |                    |
|             |             | students on |                    |
|             |             | Facebook: a |                    |
|             |             | data ethics |                    |
|             |             | p           |                    |
|             |             | erspective. |                    |
|             |             | Educational |                    |
|             |             | researcher, |                    |
|             |             | 51(8),      |                    |
|             |             | 547-550.    |                    |
+-------------+-------------+-------------+--------------------+
| 7           | October 2   | Park, J.    | Data Science in    |
|             |             | J., Kim, B. | Education, Chapter |
|             |             | H., Wong,   | 9:                 |
|             |             | N., Zheng,  | <htt               |
|             |             | J., Breen,  | ps://datasciencein |
|             |             | S., Lo, P., | education.com/c09> |
|             |             | ... & Poon, |                    |
|             |             | O. (2023).  |                    |
|             |             | Inequality  |                    |
|             |             | Beyond S    |                    |
|             |             | tandardized |                    |
|             |             | Tests:      |                    |
|             |             | Trends in   |                    |
|             |             | Extr        |                    |
|             |             | acurricular |                    |
|             |             | Activity    |                    |
|             |             | Reporting   |                    |
|             |             | in College  |                    |
|             |             | A           |                    |
|             |             | pplications |                    |
|             |             | Across Race |                    |
|             |             | and Class.  |                    |
|             |             | Technical   |                    |
|             |             | Report.     |                    |
|             |             | Annenberg   |                    |
|             |             | Institute   |                    |
|             |             | at Brown    |                    |
|             |             | University. |                    |
|             |             | \<https     |                    |
|             |             | ://edworkin |                    |
|             |             | g           |                    |
|             |             | papers.\>co |                    |
|             |             | m/ai23-749. |                    |
+-------------+-------------+-------------+--------------------+
| **8**       | **October 9 | Fischer,    |                    |
|             | (Fall B     | C., Pardos, |                    |
|             | reak)**     | Z. A.,      |                    |
|             |             | Baker, R.   |                    |
|             |             | S.,         |                    |
|             |             | Williams,   |                    |
|             |             | J. J.,      |                    |
|             |             | Smyth, P.,  |                    |
|             |             | Yu, R.,     |                    |
|             |             | \... &      |                    |
|             |             | Warschauer, |                    |
|             |             | M. (2020).  |                    |
|             |             | Mining big  |                    |
|             |             | data in     |                    |
|             |             | education:  |                    |
|             |             | Affordances |                    |
|             |             | and         |                    |
|             |             | challenges. |                    |
|             |             | Review of   |                    |
|             |             | Research in |                    |
|             |             | Education,  |                    |
|             |             | 44(1),      |                    |
|             |             | 130-160.    |                    |
|             |             |             |                    |
|             |             | Hakimi, L., |                    |
|             |             | Eynon, R.,  |                    |
|             |             | & Murphy,   |                    |
|             |             | V. A.       |                    |
|             |             | (2021). The |                    |
|             |             | ethics of   |                    |
|             |             | using       |                    |
|             |             | digital     |                    |
|             |             | trace data  |                    |
|             |             | in          |                    |
|             |             | education:  |                    |
|             |             | A thematic  |                    |
|             |             | review of   |                    |
|             |             | the         |                    |
|             |             | research    |                    |
|             |             | landscape.  |                    |
|             |             | Review of   |                    |
|             |             | Educational |                    |
|             |             | Research,   |                    |
|             |             | 91(5),      |                    |
|             |             | 671-717.    |                    |
+-------------+-------------+-------------+--------------------+
| 9           | October 16  | Kimmons,    | Towards Data       |
|             |             | R., & V     | Science, Web       |
|             |             | eletsianos, | Scraping:          |
|             |             | G. (2018).  | <https://          |
|             |             | Public      | towardsdatascience |
|             |             | internet    | .com/scraping-data |
|             |             | data mining | -from-wikipedia-ta |
|             |             | methods in  | bles-3efa04c6b53f> |
|             |             | in          |                    |
|             |             | structional |                    |
|             |             | design,     |                    |
|             |             | educational |                    |
|             |             | technology, |                    |
|             |             | and online  |                    |
|             |             | learning    |                    |
|             |             | research.   |                    |
|             |             | TechTrends, |                    |
|             |             | 62(5),      |                    |
|             |             | 492-500.    |                    |
|             |             |             |                    |
|             |             | Staudt      |                    |
|             |             | Willet, K.  |                    |
|             |             | B., &       |                    |
|             |             | Carpenter,  |                    |
|             |             | J. P.       |                    |
|             |             | (2021). A   |                    |
|             |             | tale of two |                    |
|             |             | subreddits: |                    |
|             |             | Change and  |                    |
|             |             | continuity  |                    |
|             |             | in t each   |                    |
|             |             | ing‐related |                    |
|             |             | online      |                    |
|             |             | spaces.     |                    |
|             |             | British     |                    |
|             |             | Journal of  |                    |
|             |             | Educational |                    |
|             |             | Technology, |                    |
|             |             | 52(2),      |                    |
|             |             | 714-733.    |                    |
+-------------+-------------+-------------+--------------------+
| 10          | October 23  | D'ignazio,  | Quarto with R:     |
|             |             | C., &       | <https://          |
|             |             | Klein, L.   | quarto.org/docs/co |
|             |             | F. (2020).  | mputations/r.html> |
|             |             | Data        |                    |
|             |             | feminism.   | Creating table     |
|             |             | MIT press.  | with kable and     |
|             |             | Chaper 1    | kableExtra:        |
|             |             | (In         | <https://cran.r-p  |
|             |             | troduction: | roject.org/web/pac |
|             |             | Why Data    | kages/kableExtra/v |
|             |             | Science     | ignettes/awesome_t |
|             |             | Needs       | able_in_html.html> |
|             |             | Feminism)   |                    |
+-------------+-------------+-------------+--------------------+
| 11          | October 30  | Dowell, N.  |                    |
|             |             | M., Nixon,  |                    |
|             |             | T. M., &    |                    |
|             |             | Graesser,   |                    |
|             |             | A. C.       |                    |
|             |             | (2019).     |                    |
|             |             | Group co    |                    |
|             |             | mmunication |                    |
|             |             | analysis: A |                    |
|             |             | co          |                    |
|             |             | mputational |                    |
|             |             | linguistics |                    |
|             |             | approach    |                    |
|             |             | for         |                    |
|             |             | detecting   |                    |
|             |             | soc         |                    |
|             |             | iocognitive |                    |
|             |             | roles in    |                    |
|             |             | multiparty  |                    |
|             |             | in          |                    |
|             |             | teractions. |                    |
|             |             | Behavior    |                    |
|             |             | Research    |                    |
|             |             | Methods,    |                    |
|             |             | 51,         |                    |
|             |             | 1007-1041.  |                    |
+-------------+-------------+-------------+--------------------+
| 12          | N ovember 6 | Nguyen, H., |                    |
|             |             | Lopez, J.,  |                    |
|             |             | Homer, B.,  |                    |
|             |             | Ali, A., &  |                    |
|             |             | Ahn, J.     |                    |
|             |             | (2023).     |                    |
|             |             | Reminders,  |                    |
|             |             | r           |                    |
|             |             | eflections, |                    |
|             |             | and rel     |                    |
|             |             | ationships: |                    |
|             |             | insights    |                    |
|             |             | from the    |                    |
|             |             | design of a |                    |
|             |             | chatbot for |                    |
|             |             | college     |                    |
|             |             | advising.   |                    |
|             |             | Information |                    |
|             |             | and         |                    |
|             |             | Learning    |                    |
|             |             | Sciences,   |                    |
|             |             | 124(3/4),   |                    |
|             |             | 128-146.    |                    |
+-------------+-------------+-------------+--------------------+
| 13          | N ovember   | D'Mello, S. |                    |
|             | 13          | (2017).     |                    |
|             |             | Emotional   |                    |
|             |             | learning    |                    |
|             |             | analytics.  |                    |
|             |             | Handbook of |                    |
|             |             | learning    |                    |
|             |             | analytics,  |                    |
|             |             | 115.        |                    |
+-------------+-------------+-------------+--------------------+
| 14          | N ovember   | Lucy L.,    |                    |
|             | 20          | Demszky D., |                    |
|             |             | Bromley P., |                    |
|             |             | Jurafsky D. |                    |
|             |             | (2020).     |                    |
|             |             | Content     |                    |
|             |             | analysis of |                    |
|             |             | textbooks   |                    |
|             |             | via natural |                    |
|             |             | language    |                    |
|             |             | processing: |                    |
|             |             | Findings on |                    |
|             |             | gender,     |                    |
|             |             | race, and   |                    |
|             |             | ethnicity   |                    |
|             |             | in Texas US |                    |
|             |             | history     |                    |
|             |             | textbooks.  |                    |
|             |             | AERA Open,  |                    |
|             |             | 6(3). \<<h  |                    |
|             |             | ttps://doi> |                    |
|             |             | .org        |                    |
|             |             | /10.1177/23 |                    |
|             |             | 32858       |                    |
|             |             | 420940312\> |                    |
+-------------+-------------+-------------+--------------------+
| 15          | N ovember   | Rosenberg,  |                    |
|             | 27          | J. M.,      |                    |
|             |             | Borchers,   |                    |
|             |             | C., Dyer,   |                    |
|             |             | E. B.,      |                    |
|             |             | Anderson,   |                    |
|             |             | D., &       |                    |
|             |             | Fischer, C. |                    |
|             |             | (2021). Un  |                    |
|             |             | derstanding |                    |
|             |             | public      |                    |
|             |             | sentiment   |                    |
|             |             | about       |                    |
|             |             | educational |                    |
|             |             | reforms:    |                    |
|             |             | The next    |                    |
|             |             | generation  |                    |
|             |             | science     |                    |
|             |             | standards   |                    |
|             |             | on Twitter. |                    |
|             |             | AERA open,  |                    |
|             |             | 7, 233 2858 |                    |
|             |             | 4211024261. |                    |
+-------------+-------------+-------------+--------------------+
| 16          | D ecember 4 | N/A         |                    |
+-------------+-------------+-------------+--------------------+

## University Policies

### **Academic Integrity**

An essential feature of the University of Tennessee, Knoxville is a
commitment to maintaining an atmosphere of intellectual integrity and
academic honesty. As a student of the university, I pledge that I will
neither knowingly give nor receive any inappropriate assistance in
academic work, thus affirming my own personal commitment to honor and
integrity.

### **Title IV Policy**

University of Tennessee faculty are committed to supporting our students
and upholding gender equity laws as outlined by Title IX.

Please be aware that if you choose to confide in a faculty member
regarding an issue of sexual harassment (including sexual assault,
dating violence, domestic violence, and stalking), sexual exploitation,
and retaliation (prohibited conduct) we are obligated to inform the
University's Office of Title IX. They can assist you in connecting with
all possible resources both on- and off-campus.

If you would like to speak with someone confidentially, the Student
Counseling Center (865-974-2196) and the Student Health Center
(865-974-3135) are both confidential resources.

For additional resources and information, visit titleix.utk.edu.

### University Civility Statement

Civility is genuine respect and regard for others: politeness,
consideration, tact, good manners, graciousness, cordiality, affability,
amiability and courteousness. Civility enhances academic freedom and
integrity, and is a prerequisite to the free exchange of ideas and
knowledge in the learning community. Our community consists of students,
faculty, staff, alumni, and campus visitors. Community members affect
each other's well-being and have a shared interest in creating and
sustaining an environment where all community members and their points
of view are valued and respected. Affirming the value of each member of
the university community, the campus asks that all its members adhere to
the principles of civility and community adopted by the campus:
<http://civility.utk.edu/>.

### **Disability Services**

Any student who feels s/he may need an accommodation based on the impact
of a disability should contact Student Disability Services in Dunford
Hall, at 865-974-6087, or by video relay at, 865-622-6566, to coordinate
reasonable academic accommodations.

### **Your Role in Improving Teaching and Learning Through Course Assessment**

It is our collective responsibility to improve the state of teaching and
learning. During the semester, you may be requested to assess aspects of
this course either during class or at the completion of the class. You
are encouraged to respond to these various forms of assessment as a
means of continuing to improve the quality of the UT learning
experience.

### **Basic Needs**

Any student who faces challenges securing their food or housing and
believes they may affect their performance in the course is urged to
contact the Dean of Students (974-HELP or via<https://dos.utk.edu/>) for
support. Furthermore, please contact the instructor if you are
comfortable doing so.

The instructors reserve the right to revise, alter or amend this
syllabus as necessary. Students will be notified in writing / email of
any such changes. 
